### ISSUE TITLE
Missing requirements.txt file

### ISSUE THREAD

**Issue by ayush-angelium** [wondonghyeon/face-classification#10]
requirements.txt file missing in this model so I am sharing this.

[requirements.txt](https://github.com/wondonghyeon/face-classification/files/6083141/requirements.txt)

Enjoy it

**Comment by togersonS** [comment]
my ass itch.

```Collecting dlib>=19.7
  Using cached dlib-19.24.2.tar.gz (11.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting scipy>=0.13.3
  Using cached scipy-1.2.3-cp27-cp27mu-manylinux1_x86_64.whl (24.8 MB)
Using legacy 'setup.py install' for face-recognition-models, since package 'wheel' is not installed.
Building wheels for collected packages: dlib
  Building wheel for dlib (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python2 /usr/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp3y7rf0
       cwd: /tmp/pip-install-7mnrUH/dlib
  Complete output (92 lines):
  running bdist_wheel
  running build
  running build_ext
  Building extension for Python 2.7.18 (default, Jul  1 2022, 10:30:50)
  Invoking CMake setup: 'cmake /tmp/pip-install-7mnrUH/dlib/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-7mnrUH/dlib/build/lib.linux-x86_64-2.7 -DPYTHON_EXECUTABLE=/usr/bin/python2 -DCMAKE_BUILD_TYPE=Release'
  -- The C compiler identification is GNU 11.3.0
  -- The CXX compiler identification is GNU 11.3.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Deprecation Warning at /tmp/pip-install-7mnrUH/dlib/dlib/external/pybind11/CMakeLists.txt:8 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  
  
  -- pybind11 v2.10.0
  CMake Warning (dev) at /tmp/pip-install-7mnrUH/dlib/dlib/external/pybind11/tools/FindPythonLibsNew.cmake:98 (find_package):
    Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
    are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
    the cmake_policy command to set the policy and suppress this warning.
  
  Call Stack (most recent call first):
    /tmp/pip-install-7mnrUH/dlib/dlib/external/pybind11/tools/pybind11Tools.cmake:50 (find_package)
    /tmp/pip-install-7mnrUH/dlib/dlib/external/pybind11/tools/pybind11Common.cmake:180 (include)
    /tmp/pip-install-7mnrUH/dlib/dlib/external/pybind11/CMakeLists.txt:200 (include)
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  CMake Error at /tmp/pip-build-env-1Yzr3a/overlay/lib/python2.7/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find PythonInterp: Found unsuitable version "2.7.18", but
    required is at least "3.6" (found /usr/bin/python2)
  Call Stack (most recent call first):
    /tmp/pip-build-env-1Yzr3a/overlay/lib/python2.7/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
    /tmp/pip-build-env-1Yzr3a/overlay/lib/python2.7/site-packages/cmake/data/share/cmake-3.27/Modules/FindPythonInterp.cmake:182 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    /tmp/pip-install-7mnrUH/dlib/dlib/external/pybind11/tools/FindPythonLibsNew.cmake:98 (find_package)
    /tmp/pip-install-7mnrUH/dlib/dlib/external/pybind11/tools/pybind11Tools.cmake:50 (find_package)
    /tmp/pip-install-7mnrUH/dlib/dlib/external/pybind11/tools/pybind11Common.cmake:180 (include)
    /tmp/pip-install-7mnrUH/dlib/dlib/external/pybind11/CMakeLists.txt:200 (include)
  
  
  -- Configuring incomplete, errors occurred!
  Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-1Yzr3a/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 209, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-1Yzr3a/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 194, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-1Yzr3a/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 250, in <module>
      'Topic :: Software Development',
    File "/tmp/pip-build-env-1Yzr3a/overlay/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-1Yzr3a/overlay/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "setup.py", line 130, in run
      self.build_extension(ext)
    File "setup.py", line 167, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-7mnrUH/dlib/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-7mnrUH/dlib/build/lib.linux-x86_64-2.7', '-DPYTHON_EXECUTABLE=/usr/bin/python2', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for dlib
Failed to build dlib
ERROR: Could not build wheels for dlib which use PEP 517 and cannot be installed directly
```

**Comment by togersonS** [comment]
its python2 and python3 wtf in the fuk?
