### ISSUE TITLE
unable to load model

### ISSUE THREAD

**Issue by DLeeeeeee** [wondonghyeon/face-classification#3]
when I ran:
python pred.py --img_dir test --model face_model.pkl 

got error:
Traceback (most recent call last):
  File "pred.py", line 103, in <module>
    main()
  File "pred.py", line 81, in main
    clf, labels = pickle.load(f)
TypeError: a bytes-like object is required, not 'str'

I tried pickle loading using other encoding option and also tried open file with "rb", but no good result.

Could you please tell me how to solve it? is it a version problem?
OS: ubuntu 16.04
python: 3.5

**Comment by Akashpanchal95** [comment]
If you are using the python3 then use this code to read pickle file.

` with open(model_path,'rb') as f:
        clf, labels = pickle.load(f,encoding='latin1')`

**Comment by halfendt** [comment]
Hi, this still doesn't work for me.  Here is my error now:

<ipython-input-5-0a91d9bc4514> in main(input_dir, output_dir, model_path)
     49     # load the model
     50     with open(model_path, 'rb') as f:
---> 51         clf, labels = pickle.load(f, encoding='latin1')
     52 
     53     print("classifying images in {}".format(input_dir))
ModuleNotFoundError: No module named 'copy_reg\r'

OS: windows 10
python 3.6.8
