### ISSUE TITLE
predict.py fucntion thrownig error

### ISSUE THREAD

**Issue by NarasimmanSaravana1994** [wondonghyeon/face-classification#8]
/home/narasimman/.local/lib/python3.7/site-packages/pandas/compat/__init__.py:84: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
/home/narasimman/.local/lib/python3.7/site-packages/pandas/compat/__init__.py:84: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
Traceback (most recent call last):
  File "pred.py", line 102, in <module>
    main()
  File "pred.py", line 80, in main
    clf, labels = pickle.load(f)
TypeError: a bytes-like object is required, not 'str'

--------------------------
How to resolve ?

**Comment by furkanese** [comment]
I think this should solve it.
[https://github.com/wondonghyeon/face-classification/issues/3#issuecomment-478333014](url)

**Comment by dimkadimon** [comment]
I am having the same issue. The link pasted above is empty. Any help would be greatly appreciated.

EDIT: I found the solution in the other thread:

If you are using the python3 then use this code to read pickle file.

with open(model_path,'rb') as f: clf, labels = pickle.load(f,encoding='latin1')
